version: '3'
services:
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
#    volumes:
#      - ./database:/docker-entrypoint-initdb.d

    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

#  db:
#    image: postgres:12.0-alpine
#    restart: always
#    environment:
#      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
#      - POSTGRES_DB=app
#      - POSTGRES_USER=app
#      - POSTGRES_PASSWORD=pass
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./data:/var/lib/postgersql

  nodejs:
    image: node-app:1.0
    build: ./gate-simulator
    ports:
      - '9999:9999'
